### ISSUE TITLE
Unescaped Special Characters

### ISSUE THREAD

**Issue by 7RedViolin** [7RedViolin/pySigma-backend-carbonblack#11]
## Description
Special characters like `(` and `)` are not escaped and cause errors when attempting to run the resulting query.

Sigma rule:
```
            title: Test
            status: test
            logsource:
                category: process_creation
                product: windows
            detection:
                sel:
                    Image|contains:
                    - 'value1)'
                    - 'value2)'
                    - 'value3)'
                condition: sel
```

Expected output:
```
os_type:windows (process_name:value1\)* OR process_name:value2\)* OR process_name:value3\)*)
```

Actual output:
```
os_type:windows (process_name:value1)* OR process_name:value2)* OR process_name:value3)*)
```
