### ISSUE TITLE
Additional Escaped Special Characters

### ISSUE THREAD

**Issue by threatHNTR** [7RedViolin/pySigma-backend-carbonblack#14]
Currently, some characters are not escaped when converting from Sigma to Carbon Black. Not escaping special characters can result in syntax errors.

If the following characters appear in a value in your query filter, you must escape them with a single `\`

Characters: `+ - && || ! ( ) { } [ ] ^ " ~ * ? : \ / space`

Example 1: Escaping a normal windows path c:\windows\system32\.

Note the colon and directory delimiters are escaped. The asterisk on the end is not, because it’s a wildcard, not searching for the literal asterisk character in the process path

- `process_path:c\:\\windows\\system32\\*`

Example 2: Looking for the –encoded flag in a process cmdline
- `process_cmdline:\-encoded`

Example 3: Escaping spaces
- `process_path:*Google\ Chrome*`
- `process_publisher:Google\ LLC`

Sigma Test:
```
title: Carbon Black Escaped Characters Test
id: 1228c958-e64e-4e71-92ad-7d429f4138ba
status: test
description: Testing for escaped characters
references:
    - https://docs.vmware.com/en/VMware-Carbon-Black-Cloud/services/carbon-black-cloud-user-guide.pdf
author: Hunter (@threatHNTR)
date: 2024/09/10
tags:
    - attack.execution
    - attack.t1059
logsource:
    category: process_creation
    product: windows
detection:
    selection_test:
        CommandLine|contains:
            - '\AppData\Local\Temp\'
            - '/dev/random'
            - '"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -incognito'
            - 'https://'
            - '-ExecutionPolicy bypass'
            - 'net.exe /add /domain "ESX Admins"'
            - '^'
            - '~'
            - '[]'
            - '{}'
            - '||'
            - '&&'
            - '='
            - '+'
            - '!'
    condition: 1 of selection_*
falsepositives:
    - Unknown
level: high
```

Output:

```
device_os:WINDOWS (process_cmdline:\AppData\Local\Temp\* OR process_cmdline:/dev/random* OR process_cmdline:"C\:\Program\ Files\ \(x86\)\Google\Chrome\Application\chrome.exe"\ \-incognito* OR process_cmdline:https\://* OR process_cmdline:-ExecutionPolicy\ bypass* OR process_cmdline:net.exe\ /add\ /domain\ "ESX\ Admins"* OR process_cmdline:^* OR process_cmdline:~* OR process_cmdline:[]* OR process_cmdline:{}* OR process_cmdline:||* OR process_cmdline:&&* OR process_cmdline:=* OR process_cmdline:+* OR process_cmdline:!*)
```
Syntax Errors:

![image](https://github.com/user-attachments/assets/f70ebff1-fe01-4b1b-97ab-d9dc5522a4bb)

Expected Output:

```
device_os:WINDOWS (process_cmdline:\\AppData\\Local\\Temp\\* OR process_cmdline:\/dev\/random* OR process_cmdline:\"C\:\\Program\ Files\ \(x86\)\\Google\\Chrome\\Application\\chrome.exe\"\ \-incognito* OR process_cmdline:https\:\/\/* OR process_cmdline:\-ExecutionPolicy\ bypass* OR process_cmdline:net.exe\ \/add\ \/domain\ \"ESX\ Admins\"* OR process_cmdline:\^* OR process_cmdline:\~* OR process_cmdline:\[\]* OR process_cmdline:\{\}* OR process_cmdline:\|\|* OR process_cmdline:\&\&* OR process_cmdline:\=* OR process_cmdline:\+* OR process_cmdline:\!*)
```

No Syntax Errors:

![image](https://github.com/user-attachments/assets/2e6f9d0d-29d3-43ce-9ee3-65c67d0fcdd9)

You also don't necessarily need to have a trailing wildcard, unless you are trying to find files within a path:

`process_cmdline:\\AppData\\Local\\Temp\\*`
