### ISSUE TITLE
[BUG] CbC `not` operator incorrectly applied

### ISSUE THREAD

**Issue by rc-csmith** [7RedViolin/pySigma-backend-carbonblack#5]
## Description
When using syntax like the below sigma rule, the `not` operator has an extra space appended that causes the query to error out when executing in CbC

```yml
title: Test
description: test
author: test
logsource:
    category: process_creation
    product: windows
detection:
    selection_1:
        Image:
            - 'powershell.exe'
    selection_2:
        Image:
            - 'cmd.exe'
            - 'explorer.exe
    condition: selection_1 and not selection_2
```

Resulting query:
```
(device_os:WINDOWS (process_name:powershell.exe (- (process_name:cmd.exe OR process_name:explorer.exe))))
```

Expected query:
```
(device_os:WINDOWS (process_name:powershell.exe -(process_name:cmd.exe OR process_name:explorer.exe)))
```
